id = "ember-theme"
name = "Ember Theme"
version = "0.5.0"
schema_version = 1
authors = ["blaqat <blaqat.ag@gmail.com>"]
description = "Ember theme for Zed"
repository = "https://github.com/biaqat/ember-theme-zed"
